# Build the Angular application
FROM node:22 AS builder

WORKDIR /app

# Copy application files
COPY . .

# Install dependencies and build application
RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]